### ISSUE TITLE
error package github.com/metalmatze/alertmanager-bot: no Go files in 

### ISSUE THREAD

**Issue by Shinhocheol** [metalmatze/alertmanager-bot#30] opened 2018-10-22 06:06 UTC
# go get github.com/metalmatze/alertmanager-bot
package github.com/metalmatze/alertmanager-bot: no Go files in /root/go/src/github.com/metalmatze/alertmanager-bot

**Comment by metalmatze** [comment] 2018-10-22 13:02
Duplicate of #29

**Closed by metalmatze** 2018-10-22 13:02 UTC
