### ISSUE TITLE
Is there a way to let the bot send messages to the channel?

### ISSUE THREAD

**Issue by olzorenko** [metalmatze/alertmanager-bot#118] opened 2020-06-12 08:05 UTC
Hello!

Is there any way to let the bot send notifications to the channel? Not to just TELEGRAM_ADMIN user? I didn't find any information how to configure it...
When someone else (who is not a TELEGRAM_ADMIN) with whom I've "share" the bot in Telegram tries to send a message (like /start or /status) to the bot - I see 

`level=info ts=2020-06-11T14:30:27.674551741Z caller=bot.go:252 component=telegram msg="failed to process message" err="dropped message from forbidden sender" sender_id=YYYYYYYYYY sender_username=`

It makes any sense to receive messages only to one person.

Thanks in advance!

**Comment by olzorenko** [comment] 2020-06-12 08:43
Update: Sorry, have found how to specify more then one TELEGRAM_ADMIN during startup.

But main question remains the same - is there a way to send notification messages from Alertmanager to the channel?

**Comment by metalmatze** [comment] 2020-06-12 09:19
This is a duplicate of https://github.com/metalmatze/alertmanager-bot/issues/8 and I answered it there :)

**Closed by metalmatze** 2020-06-12 09:19 UTC
