### ISSUE TITLE
Is it possible for the bot to notify me alerts automatically without typing "/alerts".

### ISSUE THREAD

**Issue by eieizahahayo** [metalmatze/alertmanager-bot#46] opened 2019-01-24 13:24 UTC
Dear, metalmatze

I am very new to the Github issue session and this is my first time asking for help. I am sorry in advance If I did say something wrong.
Is it possible for the bot to notify me automatically when alerts occur?
The bot knows that there are alerts but it will only notify me when I use "/alerts".
I don't know if I did something wrong.
Here is my docker-compose:
```
alertmanager-bot:
    image: metalmatze/alertmanager-bot:0.3.1
    container_name: alertmanager-bot
    environment:
      ALERTMANAGER_URL: http://alert_manager:9093
      BOLT_PATH: /data/bot.db
      STORE: bolt
      LISTEN_ADDR: alertmanager-bot:8080
      TELEGRAM_ADMIN: 'my-id'
      TELEGRAM_TOKEN: 'my-bot-token'
    networks: 
      - my-network
```

Thank you.

**Comment by metalmatze** [comment] 2019-01-24 13:31
Welcome to GitHub. You're doing everything right in this issue! :+1: 

You need to write `/start` to the bot. Once it has your Telegram User tracked it will start forwarding all alerts that alertmanager sends to the bot. Make sure to set up the [Webhook in Alertmanager](https://github.com/metalmatze/alertmanager-bot#alertmanager-configuration), otherwise nothing will be send to this bot.

**Comment by metalmatze** [comment] 2019-02-18 23:11
Closing, as your :+1: seems to say that the problem is resolved.

**Closed by metalmatze** 2019-02-18 23:11 UTC
