### ISSUE TITLE
alertmanager-bot telegram templates message

### ISSUE THREAD

**Issue by sandr30** [metalmatze/alertmanager-bot#31] opened 2018-10-31 12:39 UTC
Hi! Help me tune alertmanager-bot telegram templates message. 

Alertmanager.yml
```
  receiver: 'alertmananger-bot'
  routes:
    - receiver: 'alertmananger-bot'
      group_wait: 45s
      group_interval: 10s
templates:
- '/data/monitoring/alertmanager/alert.tmpl'

receivers:
- name: 'alertmananger-bot'
  webhook_configs:
 provider: telegram
  text: '{{ template "telegram_message" . }}'
  - send_resolved: true
    url: 'http://alertmanager-bot:8080'
```

Alertmanager no started and config Alertmanager.yml error. Help me
how to make alert.tmpl ?

**Comment by metalmatze** [comment] 2018-10-31 16:20
Could you share some logs with errors? Thanks

**Comment by sandr30** [comment] 2018-11-02 07:19
Don't work, message style does not change alertmanager-bot telegram templates message:

Alertmanager.yml
route:
  receiver: 'alertmananger-bot'
  routes:
    - receiver: 'alertmananger-bot'
      group_wait: 45s
      group_interval: 5m
      repeat_interval: 3h
templates:
- '/data/monitoring/alertmanager/alert.tmpl'

receivers:
- name: 'alertmananger-bot'
  webhook_configs:
  # - send_resolved: true
  # - url: 'http://alertmanager-bot:8080'
  - send_resolved: true
    url: 'http://alertmanager-bot:8080'

alert.rules.yml
groups:

- name: client
  rules:

  - alert: ClientInstanceDown
    expr: up{job="prometheus-client"} == 0
    for: 1s
    annotations:
      summary: "Instance {{ $labels.instance }} is down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} is down."

  # CPU Usage Alerts
  - alert: NodeCPUUsageWarning
    expr: (100 - (avg(irate(node_cpu{mode="idle",name="node-exporter"}[5m])) BY (instance)
      * 100)) > 75
    for: 3m
    labels:
          severity: warning
    annotations:
      summary: '{{$labels.instance}}: High CPU usage detected'
      description: '{{$labels.instance}}: CPU usage is above 75% (current value is:
        {{ $value }})'

  - alert: NodeCPUUsageCritical
    expr: (100 - (avg(irate(node_cpu{mode="idle",name="node-exporter"}[5m])) BY (instance)
      * 100)) > 90
    for: 3m
    labels:
          severity: critical
    annotations:
      summary: '{{$labels.instance}}: High CPU usage detected'
      description: '{{$labels.instance}}: CPU usage is above 90% (current value is:
        {{ $value }})'

   # Low Disk Space Alerts
  - alert: NodeLowRootDiskWarning
    expr: ((node_filesystem_size{mountpoint="/"} - node_filesystem_free{mountpoint="/"})
      / node_filesystem_size{mountpoint="/"} * 100) > 80
    for: 2m
    labels:
          severity: warning
    annotations:
      summary: '{{$labels.instance}}: Low root disk space'
      description: '{{$labels.instance}}: Root disk usage is above 80% (current value is: {{ $value }})'

### Sends posts without style
help me!

**Comment by metalmatze** [comment] 2018-11-02 13:49
I now understand your problem.
The Alertmanager sends the firing and resolved alerts to the Alertmanager Bot via a Webhook which is pure JSON. Thus no templating can be done on the alerts inside Alertmanager itself.
The templating has to be done within the Alertmanager Bot, as it converts the JSON data to a string, which is send to Telegram.

Therefore this is a duplicate of #9. Yesterday I was actually adding that feature on my local branch. I hope to finish it on the weekend. I'll let you know in #9 once the feature merges and I publish a new release with it.

**Closed by metalmatze** 2018-11-02 13:49 UTC
